export default {
  login: "ava",
  id: 53535845,
  node_id: "MDEyOk9yZ2FuaXphdGlvbjUzNTM1ODQ1",
  avatar_url: "https://avatars.githubusercontent.com/u/53535845?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/ava",
  html_url: "https://github.com/ava",
  followers_url: "https://api.github.com/users/ava/followers",
  following_url: "https://api.github.com/users/ava/following{/other_user}",
  gists_url: "https://api.github.com/users/ava/gists{/gist_id}",
  starred_url: "https://api.github.com/users/ava/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/ava/subscriptions",
  organizations_url: "https://api.github.com/users/ava/orgs",
  repos_url: "https://api.github.com/users/ava/repos",
  events_url: "https://api.github.com/users/ava/events{/privacy}",
  received_events_url: "https://api.github.com/users/ava/received_events",
  type: "Organization",
  site_admin: false,
  name: "Ava",
  company: null,
  blog: "https://ava.inc",
  location: "Global",
  email: null,
  hireable: null,
  bio: "Rapid Application Development",
  twitter_username: null,
  public_repos: 3,
  public_gists: 0,
  followers: 3,
  following: 0,
  created_at: "2019-07-31T17:25:30Z",
  updated_at: "2020-03-22T22:37:32Z",
};
